# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named home_assistant

# Build rule for target.
home_assistant: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 home_assistant
.PHONY : home_assistant

# fast build rule for target.
home_assistant/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/build
.PHONY : home_assistant/fast

src/Audio.o: src/Audio.cpp.o
.PHONY : src/Audio.o

# target to build an object file
src/Audio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/Audio.cpp.o
.PHONY : src/Audio.cpp.o

src/Audio.i: src/Audio.cpp.i
.PHONY : src/Audio.i

# target to preprocess a source file
src/Audio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/Audio.cpp.i
.PHONY : src/Audio.cpp.i

src/Audio.s: src/Audio.cpp.s
.PHONY : src/Audio.s

# target to generate assembly for a file
src/Audio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/Audio.cpp.s
.PHONY : src/Audio.cpp.s

src/Env.o: src/Env.cpp.o
.PHONY : src/Env.o

# target to build an object file
src/Env.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/Env.cpp.o
.PHONY : src/Env.cpp.o

src/Env.i: src/Env.cpp.i
.PHONY : src/Env.i

# target to preprocess a source file
src/Env.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/Env.cpp.i
.PHONY : src/Env.cpp.i

src/Env.s: src/Env.cpp.s
.PHONY : src/Env.s

# target to generate assembly for a file
src/Env.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/Env.cpp.s
.PHONY : src/Env.cpp.s

src/OpenAIClient.o: src/OpenAIClient.cpp.o
.PHONY : src/OpenAIClient.o

# target to build an object file
src/OpenAIClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/OpenAIClient.cpp.o
.PHONY : src/OpenAIClient.cpp.o

src/OpenAIClient.i: src/OpenAIClient.cpp.i
.PHONY : src/OpenAIClient.i

# target to preprocess a source file
src/OpenAIClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/OpenAIClient.cpp.i
.PHONY : src/OpenAIClient.cpp.i

src/OpenAIClient.s: src/OpenAIClient.cpp.s
.PHONY : src/OpenAIClient.s

# target to generate assembly for a file
src/OpenAIClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/OpenAIClient.cpp.s
.PHONY : src/OpenAIClient.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/home_assistant.dir/build.make CMakeFiles/home_assistant.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... home_assistant"
	@echo "... src/Audio.o"
	@echo "... src/Audio.i"
	@echo "... src/Audio.s"
	@echo "... src/Env.o"
	@echo "... src/Env.i"
	@echo "... src/Env.s"
	@echo "... src/OpenAIClient.o"
	@echo "... src/OpenAIClient.i"
	@echo "... src/OpenAIClient.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
